language: python
python:
 - "2.7"
 - "3.6"

#
# Command to install dependencies.
#
install:
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls
  - pip install -r test-requirements.txt

#
# Run tests + coverage.
#
script: py.test --cov-config .coveragerc --cov-report= --cov=.

#
# Send coverage report to coveralls.io
#
after_success:
  - coveralls

notifications:
    email: false
