target-version = "py310"
exclude = ["_version.py"]

[lint]
# List of rules: https://docs.astral.sh/ruff/rules/
extend-select = [
  "I",   # isort
  "UP"   # Upgrade Python
]
ignore = [
    "E501" # Line too long
]

[lint.isort]
known-local-folder = ["hdx"]
